on:
  push:
    branches:
      -master
name: production deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu 18.04
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fatch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: 203.190.153.19
        ftp-username: user
        ftp-password: relaxadmin@123
        ftp-port: 22
        ftp-path: /var/www/test
